stages:
    - build
    - test

variables:
    INDEX_FILE: index.js

build Bot:
    stage: build
    image: node:16-alpine
    script:
        - yarn install 
        - yarn build
    artifacts: 
        paths: 
            - dist

test Bot:
    stage: test
    image: node:16-alpine
    script:
        - test -f dist/$INDEX_FILE
